// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOuJWX481ew3BFMO-PmA3Bu9unYqz8sLY',
    appId: '1:507148486691:web:228fbda5bdc91b24b84996',
    messagingSenderId: '507148486691',
    projectId: 'dadado-ccce9',
    authDomain: 'dadado-ccce9.firebaseapp.com',
    storageBucket: 'dadado-ccce9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj2ctPzgVQJ2WEt02s0HltdCcQ9Cq0wJ4',
    appId: '1:507148486691:android:775a2753728c7384b84996',
    messagingSenderId: '507148486691',
    projectId: 'dadado-ccce9',
    storageBucket: 'dadado-ccce9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFvnpKikMW4Ugp5a-pefhHq8L-O_ESKyk',
    appId: '1:507148486691:ios:ee59bdc3b7a8ce7bb84996',
    messagingSenderId: '507148486691',
    projectId: 'dadado-ccce9',
    storageBucket: 'dadado-ccce9.firebasestorage.app',
    iosBundleId: 'com.example.dadado',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFvnpKikMW4Ugp5a-pefhHq8L-O_ESKyk',
    appId: '1:507148486691:ios:ee59bdc3b7a8ce7bb84996',
    messagingSenderId: '507148486691',
    projectId: 'dadado-ccce9',
    storageBucket: 'dadado-ccce9.firebasestorage.app',
    iosBundleId: 'com.example.dadado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOuJWX481ew3BFMO-PmA3Bu9unYqz8sLY',
    appId: '1:507148486691:web:1155a8dbbcbe8731b84996',
    messagingSenderId: '507148486691',
    projectId: 'dadado-ccce9',
    authDomain: 'dadado-ccce9.firebaseapp.com',
    storageBucket: 'dadado-ccce9.firebasestorage.app',
  );
}
